### ISSUE TITLE
Revisar vista de carrito

### ISSUE THREAD

**Issue by RodrigoMoralesV** [RodrigoMoralesV/softech-ecommerce#10]
Esta tarea es para que por favor revises la vista de carrito (solo revisar, no pido nada funcional aun) para ver que otras cosas visuales podríamos agregarle (sombras, fondos etc) recuerda seguir la paleta de colores que nos otorgo Joan.

Aqui esta la documentacion de bootstrap por si la necesitas: https://getbootstrap.com/docs/4.0/getting-started/introduction/

Y recuerda, por favor nada de estilos en el mismo archivo

**Comment by richard780** [comment]
bro hace reatisimo revise la seccion de carrito

**Comment by richard780** [comment]
.
