### ISSUE TITLE
Arreglar vista de Busqueda

### ISSUE THREAD

**Issue by RodrigoMoralesV** [RodrigoMoralesV/softech-ecommerce#13]
Por algun motivo en la vista de los resultados de busqueda (por ahora es /shop), los items se ven de esta forma:

![Image](https://github.com/RodrigoMoralesV/softech-ecommerce/assets/132719865/6ad2a621-36cd-44e8-be45-7782c3e45e8b)

En lugar de verse asi:

![Image](https://github.com/RodrigoMoralesV/softech-ecommerce/assets/132719865/a937dc28-6088-48ac-99ee-9b5ad33e591d)

Quisiera que por favor soluciones esto

**Comment by jscortes23** [comment]
Dame el archivo de la plantilla, tal vez sea porque en esa vista usan un CSS de más
